spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: API-SERVICE
          uri: lb://API-SERVICE
          predicates:
            - Path=/app/**
        - id: CHAT
          uri: lb://CHAT
          predicates:
            - Path=/web/**
        - id: CHAT
          uri: lb://CHAT
          predicates:
            - Path=/admin/**
        - id: CHAT
          uri: lb://CHAT
          predicates:
            - Path=/api/**
        - id: CHAT
          uri: lb://CHAT
          predicates:
            - Path=/login
        - id: CHAT
          uri: lb://CHAT
          predicates:
            - Path=/
