spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CHAT
          uri: lb://CHAT
          predicates:
            - Path=/user/**
        - id: API-SERVICE
          uri: lb://API-SERVICE
          predicates:
            - Path=/api/**
